# Autoscaling para back1-ventas
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-back1-ventas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back1-ventas
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
# Autoscaling para back2-despacho
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-back2-despacho
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back2-despacho
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50